# For more information: https://laravel.com/docs/sail
version: '3'
services:
  application:
    # image: php:fpm
    restart: unless-stopped
    build:
       context: ./docker/config/php/
       dockerfile: Dockerfile
       args:
         - CODE_ENV=local
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - studio_rf-net
    tty: true
    volumes:
      - .:/var/www/html
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - database
  database:
    restart: unless-stopped
    image: 'mysql/mysql-server:latest'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    volumes:
      - 'studio_rf:/var/lib/mysql'
      - ./docker/config/database/_dumps:/_dumps:rw,cached
      # delegated'
      # /etc/mysql/conf.d for x64
      # for arm image
      # - './docker/config/mysql/my.cnf:/etc/my.cnf'
    networks:
      - studio_rf-net
    tty: true
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT:-80}:80"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '.:/var/www/html'
      - ./docker/config/nginx/site.conf:/etc/nginx/conf.d/default.conf
      # so we can cache our github tokens
      - '~/.composer/docker-cache/:/root/.composer:cached'
      - '~/.config/composer/:/root/.config/composer:cached'
      - vscode-extensions:/root/.vscode-server/extensions
    networks:
      - studio_rf-net
    tty: true
    links:
      - application
    depends_on:
      - database
    restart: unless-stopped
networks:
  studio_rf-net:
    driver: bridge
volumes:
  studio_rf:
    driver: local
  vscode-extensions:
    driver: local
